language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t ko12ztwe/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true ko12ztwe/react-test-app npm test

after_success:
  - docker build -t ko12ztwe/docker-frontend ./frontend
  - docker build -t ko12ztwe/docker-backend ./backend
  - docker build -t ko12ztwe/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push ko12ztwe/docker-frontend
  - docker push ko12ztwe/docker-backend
  - docker push ko12ztwe/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: "elasticbeanstalk-us-west-1-862604873599"
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
